# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Alien.github.io',
                'doc_host': 'https://Tomiarry.github.io',
                'git_url': 'https://github.com/Tomiarry/Alien.github.io',
                'lib_path': 'Alien.github.io'},
  'syms': {'Alien.github.io.core': {'Alien.github.io.core.foo': ('core.html#foo', 'Alien.github.io/core.py')}}}
